services:
  - type: web
    name: meeting-backend-scheduler
    runtime: node
    plan: free
    rootDir: backend
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: MONGO_URI
        value: mongodb+srv://dhia:dhia123@cluster0.m8iegv8.mongodb.net/meeting_app?retryWrites=true&w=majority
      - key: PORT
        value: 5001
